name: Build and Deploy Express Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: SSH Setup

        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          cd /home/runner/work/node-gh-actions
          ls -a
          pwd

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude=".git/"
          path: node-gh-actions/node-gh-actions/
          remote_path: ${{secrets.SERVER_PATH}}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{secrets.SERVER_USERNAME}}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
